/** @format */

import {
  APP_LIMITS_PERSIST_VERSION,
  MMKV_INSTANCE_ID,
  MONITORING_PERSIST_VERSION,
  PERSIST_STORAGE_KEYS,
  SELECTED_APPS_PERSIST_VERSION,
  SETTINGS_PERSIST_VERSION,
} from '@/store/persistSchema';

/**
 * Contract mirrored in `android/.../storage/PersistSchema.kt`.
 * Update both files together when keys or versions change.
 */
const ANDROID_PERSIST_CONTRACT = {
  MMKV_INSTANCE_ID: 'focus-guard-storage',
  SELECTED_APPS_STORAGE_KEY: 'selected-apps-storage',
  APP_LIMITS_STORAGE_KEY: 'app-limits-storage',
  MONITORING_STORAGE_KEY: 'monitoring-storage',
  SETTINGS_STORAGE_KEY: 'settings-storage',
  SELECTED_APPS_PERSIST_VERSION: 1,
  APP_LIMITS_PERSIST_VERSION: 1,
  MONITORING_PERSIST_VERSION: 1,
  SETTINGS_PERSIST_VERSION: 1,
} as const;

describe('persistSchema', () => {
  it('keeps the JS contract aligned with Android PersistSchema.kt', () => {
    expect(MMKV_INSTANCE_ID).toBe(ANDROID_PERSIST_CONTRACT.MMKV_INSTANCE_ID);
    expect(PERSIST_STORAGE_KEYS.selectedApps).toBe(ANDROID_PERSIST_CONTRACT.SELECTED_APPS_STORAGE_KEY);
    expect(PERSIST_STORAGE_KEYS.appLimits).toBe(ANDROID_PERSIST_CONTRACT.APP_LIMITS_STORAGE_KEY);
    expect(PERSIST_STORAGE_KEYS.monitoring).toBe(ANDROID_PERSIST_CONTRACT.MONITORING_STORAGE_KEY);
    expect(PERSIST_STORAGE_KEYS.settings).toBe(ANDROID_PERSIST_CONTRACT.SETTINGS_STORAGE_KEY);
    expect(SELECTED_APPS_PERSIST_VERSION).toBe(ANDROID_PERSIST_CONTRACT.SELECTED_APPS_PERSIST_VERSION);
    expect(APP_LIMITS_PERSIST_VERSION).toBe(ANDROID_PERSIST_CONTRACT.APP_LIMITS_PERSIST_VERSION);
    expect(MONITORING_PERSIST_VERSION).toBe(ANDROID_PERSIST_CONTRACT.MONITORING_PERSIST_VERSION);
    expect(SETTINGS_PERSIST_VERSION).toBe(ANDROID_PERSIST_CONTRACT.SETTINGS_PERSIST_VERSION);
  });
});
