/** @format */

import type { PermissionId } from '@/screen/EnablePermissions/types';

const toSegment = (value: string) => value.replace(/[^a-zA-Z0-9-_]/g, '-');

export const testIds = {
  app: {
    loader: 'app-loader',
    usageLoader: 'app-usage-loader',
  },
  onboarding: {
    screen: 'onboarding-screen',
    skipButton: 'onboarding-skip-button',
    continueButton: 'onboarding-continue-button',
    stepIndicator: 'onboarding-step-indicator',
    walkthroughPager: 'onboarding-walkthrough-pager',
    walkthroughStep: (stepId: string) => `onboarding-step-${toSegment(stepId)}`,
  },
  enablePermissions: {
    screen: 'enable-permissions-screen',
    cards: 'enable-permissions-cards',
    header: 'enable-permissions-header',
    privacyNotice: 'enable-permissions-privacy-notice',
    continueButton: 'enable-permissions-continue-button',
    permissionCard: (id: PermissionId) => `permission-card-${id}`,
    grantButton: (id: PermissionId) => `grant-permission-${id}`,
    grantedBadge: (id: PermissionId) => `permission-granted-badge-${id}`,
  },
  dashboard: {
    screen: 'dashboard-screen',
    scroll: 'dashboard-scroll',
    header: 'dashboard-header',
    greeting: 'dashboard-greeting',
    settingsButton: 'dashboard-settings-button',
    focusOverview: 'dashboard-focus-overview',
    dailyStats: 'dashboard-daily-stats',
    quickActions: 'dashboard-quick-actions',
    focusModeButton: 'dashboard-focus-mode-button',
    manageAppsButton: 'dashboard-manage-apps-button',
    distractingAppsSection: 'dashboard-distracting-apps-section',
    viewAllAppsButton: 'dashboard-view-all-apps-button',
    appsList: 'dashboard-apps-list',
    appsEmpty: 'dashboard-apps-empty',
    usageLoader: 'dashboard-usage-loader',
    appRow: (packageName: string) => `dashboard-app-row-${toSegment(packageName)}`,
  },
  trackedApps: {
    screen: 'tracked-apps-screen',
    list: 'tracked-apps-list',
    header: 'tracked-apps-header',
    backButton: 'tracked-apps-back-button',
    appCount: 'tracked-apps-count',
    empty: 'tracked-apps-empty',
    usageLoader: 'tracked-apps-usage-loader',
    appRow: (packageName: string) => `tracked-apps-row-${toSegment(packageName)}`,
  },
  legal: {
    dataPrivacy: {
      screen: 'data-privacy-screen',
      scroll: 'data-privacy-scroll',
      header: 'data-privacy-header',
      backButton: 'data-privacy-back-button',
    },
    termsPrivacy: {
      screen: 'terms-privacy-screen',
      scroll: 'terms-privacy-scroll',
      header: 'terms-privacy-header',
      backButton: 'terms-privacy-back-button',
    },
  },
  settings: {
    screen: 'settings-screen',
    scroll: 'settings-scroll',
    header: 'settings-header',
    backButton: 'settings-back-button',
    preferencesSection: 'settings-preferences-section',
    privacySection: 'settings-privacy-section',
    privacyBanner: 'settings-privacy-banner',
    footer: 'settings-footer',
    version: 'settings-version',
    termsButton: 'settings-terms-button',
    notificationsRow: 'settings-notifications-row',
    notificationsToggle: 'settings-notifications-toggle',
    linkRow: (id: string) => `settings-link-row-${toSegment(id)}`,
  },
  configureLimits: {
    screen: 'configure-limits-screen',
    unknownAppScreen: 'configure-limits-unknown-app',
    scroll: 'configure-limits-scroll',
    header: 'configure-limits-header',
    backButton: 'configure-limits-back-button',
    appBadge: (packageName: string) => `configure-limits-app-${toSegment(packageName)}`,
    warningCard: 'configure-limits-warning-card',
    warningDecrease: 'configure-limits-warning-decrease',
    warningIncrease: 'configure-limits-warning-increase',
    warningTrack: 'configure-limits-warning-track',
    hardBlockCard: 'configure-limits-hard-block-card',
    hardBlockDecrease: 'configure-limits-hard-block-decrease',
    hardBlockIncrease: 'configure-limits-hard-block-increase',
    hardBlockTrack: 'configure-limits-hard-block-track',
    strictModeCard: 'configure-limits-strict-mode-card',
    strictModeToggle: 'configure-limits-strict-mode-toggle',
    saveButton: 'configure-limits-save-button',
    dailyUsageCard: (packageName: string) => `configure-limits-daily-usage-${toSegment(packageName)}`,
  },
  manageApps: {
    screen: 'manage-apps-screen',
    scroll: 'manage-apps-scroll',
    header: 'manage-apps-header',
    backButton: 'manage-apps-back-button',
    selectedCount: 'manage-apps-selected-count',
    searchField: 'manage-apps-search-field',
    searchInput: 'manage-apps-search-input',
    categoryFilters: 'manage-apps-category-filters',
    categoryFilter: (category: string) => `manage-apps-category-${toSegment(category)}`,
    selectedSection: 'manage-apps-selected-section',
    selectedAppsScroll: 'manage-apps-selected-apps-scroll',
    selectedChip: (packageName: string) => `manage-apps-selected-chip-${toSegment(packageName)}`,
    selectedChipPress: (packageName: string) => `manage-apps-selected-chip-press-${toSegment(packageName)}`,
    selectedChipRemove: (packageName: string) => `manage-apps-selected-chip-remove-${toSegment(packageName)}`,
    appsList: 'manage-apps-list',
    appsFilterLoader: 'manage-apps-filter-loader',
    appsLoader: 'manage-apps-loader',
    appsEmpty: 'manage-apps-empty',
    appRow: (packageName: string) => `manage-apps-row-${toSegment(packageName)}`,
    appSelectionControl: (packageName: string) => `manage-apps-selection-${toSegment(packageName)}`,
  },
} as const;
